### ISSUE TITLE
Add the ability of overloading toast messages from PrimeDatePickerBottomSheet

### ISSUE THREAD

**Issue by tlonski** [aminography/PrimeDatePicker#11]
Hello @aminography,
Could you add the ability to change the displayed messages from the class PrimeDatePickerBottomSheet?

That's toasts: 
Line 84: **toast("No day is selected!")**
Line 92: **toast("No range is selected!")**

**Comment by aminography** [comment]
Hi @tlonski 
Thanks for your reporting issue. Please update the library version to 1.0.13, then see this: https://github.com/aminography/PrimeDatePicker#customizing-texts-in-date-picker-bottom-sheet
