### ISSUE TITLE
Function named goto unable to use in java file

### ISSUE THREAD

**Issue by kc18797** [aminography/PrimeDatePicker#15]
Change the function named goto in PrimeCalenderview.kt file, as goto label is already reserved by java and is not used as a function name.

Also provide the functionality to add the arrow buttons, for next and previous month on click.

Is there any option to slow down scroll or to give maximum no of months while scrolling. Also, it will be helpful if the scroll is disabled and only buttons will work.

**Comment by aminography** [comment]
Thanks for your reporting issue. It will be fixed on the next version soon.

**Comment by aminography** [comment]
An alternative goto function has been provided (goTo) to be able to use it in java. Other recommendations will be added in future releases.

**Comment by aminography** [comment]
Moved to #30 .
