### ISSUE TITLE
Color Customisation

### ISSUE THREAD

**Issue by Ab3id** [aminography/PrimeDatePicker#16]
Tried setting custom style to the bottom dialog, but it doesnot change the colors.
how to change the  stripe showing selected date color.?

**Comment by EsmaeelNabil** [comment]
you can take this file 
src/main/res/layout/fragment_date_picker_bottom_sheet.xml
from the library and CHANGE the colors you want in it by doing that you are overriding it

**Comment by aminography** [comment]
Till now, I didn't consider color customization for the bottom sheet. But in the future I provide it. By the way, the solution suggested by @EsmaeelNabil is right. You can customize the PrimeCalendarView inside it using [XML-Attributes](https://github.com/aminography/PrimeDatePicker/#1-xml-attributes) then put the XML file in your project's layout directory which overrides the library's XML.

**Comment by aminography** [comment]
In version 3.0.0, you can completely customize the theme including the selection stripe color.
