### ISSUE TITLE
Leaking Memory

### ISSUE THREAD

**Issue by Presheda** [aminography/PrimeDatePicker#17]
Leak Canary reported that the `OnDayPickedListener()` is causing a memory leak.
is there a way to remove the listener when i no longer need it.

**Comment by aminography** [comment]
Sure. I'll provide it in the next version. Thanks for reporting the issue.

**Comment by Presheda** [comment]
That will be great. Thank you.

**Comment by aminography** [comment]
Please update the library to version `2.0.0` then use `datePicker.setDayPickCallback(null)`. 
Some basic changes have happened in this version. You can see how to create the `PrimeDatePickerBottomSheet` in [develop/DatePickerActivity.kt](https://github.com/aminography/PrimeDatePicker/blob/develop/sample-app/src/main/java/com/aminography/primedatepicker/sample/view/DatePickerActivity.kt)
However, the main page documentation will be completed in next days.

**Comment by Presheda** [comment]
Could you please give a Java doc ?

**Comment by aminography** [comment]
Yes, sure, soon.
