### ISSUE TITLE
Is it possible to disable specific dates?

### ISSUE THREAD

**Issue by MeigaraJuma** [aminography/PrimeDatePicker#19]
I was trying to disable some date or like .setSelectableDays method in Material Date Picker.
Is it possible in PrimeDatePicker? Because as far as i know, it only disable minimum or maximum date.

**Comment by aminography** [comment]
Currently, this functionality is not implemented. I'll provide it in the next version.

**Comment by aminography** [comment]
In version [3.0.0](https://github.com/aminography/PrimeDatePicker#version-300), you'll be able to set a list of days that are disabled like the following:
```kotlin
val datePicker = PrimeDatePicker.bottomSheetWith(today)
        .pickMultipleDays(multipleDaysPickCallback)
        .disabledDays(disabledDaysList)
        .build()
```
