### ISSUE TITLE
multiple select for dates

### ISSUE THREAD

**Issue by Azinnilchi** [aminography/PrimeDatePicker#2]
hi, I've searched a lot for Persian library and your library was the best !! I just wanted to select multiple dates from my code and show it in a calendar with a different color! is this possible?! if so, how can I achieve this?! 
again, thank you for your awesome library

**Comment by aminography** [comment]
Hi;
Thanks for your positive opinion. In a short time, I apologize to say that I can't implement it. However, you can pull the code and implement it yourself. Finally, I'll implement this feature in the next month.
