### ISSUE TITLE
Is it possible to access to OnDayPickedListener from PrimeDatePickerBottomSheet?

### ISSUE THREAD

**Issue by mespinosag** [aminography/PrimeDatePicker#20]
I am using the PrimeDatePickerBottomSheet with the option pickMultipleDays, so I use the listener MultipleDaysPickCallback, that notices me when the user clicks the final "Select" and finish the selection. But the problem is that I need also a listener that notices me when the user selects a day (a single day. If the user selects 10 days I would need to be noticed the 10 times, not just the last one when he clicks "Select"). 
I have been studying the library and I have found that this is possible with PrimeCalendarView using onDayPickedListener (actually its parameter: multipleDays: List<PrimeCalendar> tells you the list of days you have selected and it triggers when the user selects a day, always), but this is not open in PrimeDatePickerBottomSheet, so I wondered if you could add it in a future version.

Thank you so much for the amazing work you do with this library and sorry to disturb!

**Comment by aminography** [comment]
Hi Marina;
I really appreciate your consideration.
I'm adding this functionality and it's available in the next version.
If you want to, I can release an intermediate version that addresses the issue.

**Comment by aminography** [comment]
The next version (v3) contains some structural changes. However, you can see that `setOnDayPickedListener` is added in [PrimeDatePicker](https://github.com/aminography/PrimeDatePicker/blob/feature_theme/library/src/main/java/com/aminography/primedatepicker/picker/PrimeDatePicker.kt).

**Comment by mespinosag** [comment]
If you can release an intermediate version I would be really happy.
Thank you for everything, you are a god!

**Comment by aminography** [comment]
Sure, I'll do this soon.
You're welcome. Thank you too.

**Comment by aminography** [comment]
Version [3.0.0](https://github.com/aminography/PrimeDatePicker#version-300) has been released. So you'll be able to use the `setOnEachDayPickedListener` like the following:
```kotlin
val datePicker = PrimeDatePicker.bottomSheetWith(today)
         ...
        .build()

datePicker.setOnEachDayPickedListener(onDayPickedListener)
```

**Comment by mespinosag** [comment]
Thank you. I already tested this and it works perfectly!

However, I have found a minor bug (its not important, I just say it in case you didn't realise about it). When I set firstDayOfWeek for example to Monday (Calendar.MONDAY) it is working ok and the week starts on Monday, but when I click on the month label to go to another month (for example December 2020) and I go to that month, then the week doesn't start on Monday anymore (in my case it changes to start on Sunday).
I also noticed all of my FloatingActionButton backgound color changed to some kind of green after upgrading the library version. This may be a more important issue.

Thank you again and I hope this helps you.

**Comment by aminography** [comment]
Thank you, Marina, for your help.
I've fixed the problem in firstDayOfWeek. (Version [3.0.1](https://github.com/aminography/PrimeDatePicker#version-301))
About the second, I don't understand what's happening. Is it possible to share more data, such as screenshots, *etc*?

**Comment by mespinosag** [comment]
Yes, when I set the version to 2.0.0 my FloatingActionButton are like this (being this green my primary color): 
![image](https://user-images.githubusercontent.com/64549202/80976233-78ce3180-8e23-11ea-8584-e73b1c28d32a.png)

But when I upgrade the version to 3.0.0 my FloatingActionButton looks like this:
![image](https://user-images.githubusercontent.com/64549202/80976624-f4c87980-8e23-11ea-9d7d-04bd6e94865c.png)


This is the code:
        <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/bt_holiday_request"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginEnd="16dp"
            android:layout_marginBottom="16dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:srcCompat="@drawable/ic_add" />

It is not a big issue because if I set android:backgroundTint="@color/colorPrimary" it is fixed but this is probably happening to everyone who uses FloatingActionButton like this.

**Comment by aminography** [comment]
There are no styles in the library. Two possibilities exist:
1. Have you used any resources in your project with names like colors in [material_colors.xml](https://github.com/aminography/PrimeDatePicker/blob/master/library/src/main/res/values/material_colors.xml) file?
2. What's the version of your project's material dependency? In the library I used 
`'com.google.android.material:material:1.1.0'`.

**Comment by mespinosag** [comment]
I don't use any names in material_colors.xml file.
And actually I just realised that I didn't add 'com.google.android.material:material:1.1.0' dependency so I was probably using it because another library included it.
But we can forget about this, it is not a big issue and if your library don't include styles it is probably because of the material library then.

By the way, in the version 3.0.1 the problem with _firstDayOfWeek_ it is fixed when you go to another month when clicking in the month label but it is not fixed when you click in the recyclerview item (the recyclerview that shows all the days you have selected) and it has to navigate to that date.
Sorry If I am disturbing too much ^^U

**Comment by aminography** [comment]
I have fixed it. Please upgrade the library to version 3.0.2.
I really appreciate your help leading to improve this tool. Also, I'm sorry because of the raised problems.
