### ISSUE TITLE
Get the month currently displayed

### ISSUE THREAD

**Issue by TranVanDinh235** [aminography/PrimeDatePicker#33]
Hi, I want to get the month showing, how can I do it?

**Comment by aminography** [comment]
Hi;
Where do you need it? `PrimeDatePicker` or `PrimeCalendarView`?

**Comment by TranVanDinh235** [comment]
In PrimeCalendarView with typePicker=MULTIPLE, I want to create a button when I click on it, the entire day of the month is selected. So, how can i achieve this?

**Comment by aminography** [comment]
Please upgrade to the version to `3.2.0`.
A property named `firstDayOfMonthCalendar` is provided to deliver information about the first day of the currently visible month. Then, you can filter picked days by its year and month like the following:

```kotlin
val firstDayOfMonth = calendarView.firstDayOfMonthCalendar
val days = calendarView.pickedMultipleDaysList.filter {
    it.year == firstDayOfMonth?.year && it.month == firstDayOfMonth.month
}
```

**Comment by aminography** [comment]
Please give an ⭐ if you enjoy the library 😃.

**Comment by TranVanDinh235** [comment]
It works very well ⭐️😁
