### ISSUE TITLE
Update Selected MultiDate

### ISSUE THREAD

**Issue by sripati** [aminography/PrimeDatePicker#37]
Is it possible, whatever I have selected previous selection should display next time. I mean, I want to show pre-selected dates while showing dialog box.

**Comment by aminography** [comment]
Hi @sripati,
Absolutely. Using `initiallyPickedSingleDay`, `initiallyPickedMultipleDays`, `initiallyPickedRangeDays` on the builder you can achieve this.
For example:

```
val datePicker = PrimeDatePicker.bottomSheetWith(today)
        .pickMultipleDays(multipleDaysPickCallback)
        .initiallyPickedMultipleDays(listOfDays)  // <--
        .build()

datePicker.show(supportFragmentManager, "SOME_TAG")
```
