### ISSUE TITLE
How in range calendar highlight "From" date at start?

### ISSUE THREAD

**Issue by Pirokar** [aminography/PrimeDatePicker#41]
When calendar starting, I want to see already picked "from" date.

**Comment by aminography** [comment]
You could do it using `initiallyPickedRangeDays` passing the similar start day and end day. However, I've added a better feature for this. Please update the library to version `3.3.1` then you'll be able to specify the start day using `initiallyPickedStartDay`.
For example:

```
val datePicker = PrimeDatePicker.bottomSheetWith(today)
        .pickRangeDays(rangeDaysPickCallback)
        .initiallyPickedStartDay(an_Instance_of_prime_calendar_as_start_day)  // <--
        .build()

datePicker.show(supportFragmentManager, "SOME_TAG")
```
