### ISSUE TITLE
Want to set custom date

### ISSUE THREAD

**Issue by ParthJadav** [aminography/PrimeDatePicker#43]
Hey, I want to set custom date with selected. Could you please help me in that ?

**Comment by aminography** [comment]
Hi @ParthJadav,
If you mean you want to show the date picker with preselected date, usin `initiallyPickedSingleDay`, `initiallyPickedMultipleDays`, `initiallyPickedRangeDays` on the builder you can achieve this.
For example:

```
val datePicker = PrimeDatePicker.bottomSheetWith(today)
        .pickMultipleDays(multipleDaysPickCallback)
        .initiallyPickedMultipleDays(listOfDays)  // <--
        .build()

datePicker.show(supportFragmentManager, "SOME_TAG")
```
