### ISSUE TITLE
The BottomSheet has sharp edges instead of rounded one.

### ISSUE THREAD

**Issue by rama-2402** [aminography/PrimeDatePicker#46]
The BottomSheet in sample app provided works fine and has rounded corners but for some reason using the library in the app i'm developing, 

1. Then BottomSheet is rectangle. When used dark theme/ dark background color it shows small white filled spaces. 
![Screenshot_2021-01-24-19-52-42-37_3917da0d403222df0ac037cc35ea96cb](https://user-images.githubusercontent.com/68183781/105633307-d9077680-5e7d-11eb-99fd-28926c572ecc.jpg)

Is there any fix for this?

BTW Thank you so much for this library. I love every bit of it and how easy it is to impliment it!!

**Comment by aminography** [comment]
Hi @rama-2402,
Thank you for reporting this issue. Could you please tell me what is the API level of the phone you are testing on? Does it occur on every device? 
You're welcome:))))

**Comment by rama-2402** [comment]
Hi @aminography  Thanks so much for responding. Yes! it is having this sharp edges on all the phones i have tested. I have tested it on Android 10, 9 Realme devices, also on API 22 on my android studio emulator. Everything works great except the corner radius.

**Comment by aminography** [comment]
NP :) 
It means that in your app theme, there is something that sets a white background for `BottomSheet`s and we should find it. If it's possible to you, please show me the styles of the app which are related to the theme.

**Comment by rama-2402** [comment]
Hi @aminography sorry for the delayed response. Here is my themes.xml file

<resources xmlns:tools="http://schemas.android.com/tools">
    
    <style name="Pillglassmorphism" parent="Theme.MaterialComponents.NoActionBar">
        
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/blue_background</item>
        <item name="colorOnPrimary">@color/white</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        
        <item name="android:windowAnimationStyle">@style/CustomActivityAnimation</item>
    </style>
    <style name="CustomActivityAnimation" parent="@android:style/Animation.Activity">
        <item name="android:activityOpenEnterAnimation">@anim/slide_in_right</item>
        <item name="android:activityOpenExitAnimation">@anim/slide_out_left</item>
        <item name="android:activityCloseEnterAnimation">@anim/slide_in_left</item>
        <item name="android:activityCloseExitAnimation">@anim/slide_out_right</item>
    </style>
    <style name="Circular">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>
</resources>

**Comment by rama-2402** [comment]
Hi @aminography sorry for the delayed response. Here is my themes.xml file

<resources xmlns:tools="http://schemas.android.com/tools">
    
    <style name="Pillglassmorphism" parent="Theme.MaterialComponents.NoActionBar">
        
        <item name="colorPrimary">@color/purple_500</item>
        <item name="colorPrimaryVariant">@color/blue_background</item>
        <item name="colorOnPrimary">@color/white</item>
        
        <item name="colorSecondary">@color/teal_200</item>
        <item name="colorSecondaryVariant">@color/teal_700</item>
        <item name="colorOnSecondary">@color/black</item>
        
        <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
        
        <item name="android:windowAnimationStyle">@style/CustomActivityAnimation</item>
    </style>
    <style name="CustomActivityAnimation" parent="@android:style/Animation.Activity">
        <item name="android:activityOpenEnterAnimation">@anim/slide_in_right</item>
        <item name="android:activityOpenExitAnimation">@anim/slide_out_left</item>
        <item name="android:activityCloseEnterAnimation">@anim/slide_in_left</item>
        <item name="android:activityCloseExitAnimation">@anim/slide_out_right</item>
    </style>
    <style name="Circular">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50%</item>
    </style>
</resources>
