### ISSUE TITLE
Labels text change and hijri calendar language

### ISSUE THREAD

**Issue by AazifNP** [aminography/PrimeDatePicker#53]
Can you make an update where I can change the labels. i.e the "Select" and "Cancel", because for Saudi Arabia, the Arabic translation of "Select" is a different word, not the one that is shown.
Also can you make another update where the Hijri calendar is shown in English as well. Not just Arabic.
Thank you! Looking forward to your response.

**Comment by aminography** [comment]
Hi Aazif,
Sure. I'll make it possible to change the text soon. However, it would be great if you could contribute to improving the Arabic translations. Please let me know about the right texts.

**Comment by AazifNP** [comment]
Hi aminography, 
The only issue was with the "Select" where it should be "اختر"

**Comment by AazifNP** [comment]
Dear Aminography, 
Any update?

**Comment by aminography** [comment]
@AazifNP: Sorry for the late answer. I'll update the library soon.

**Comment by AazifNP** [comment]
@aminography thank you! Do let me know once you've made the update

**Comment by seifeibrahim** [comment]
Hello @aminography 

I need the same change, Could you update it please ?

Select text to be "اختيار" not "انتخب"

Thanks a lot

**Comment by aminography** [comment]
Hi! Please update the library dependency to `3.6.1` or above.
