### ISSUE TITLE
Migrate artifacts from JCenter to MavenCentral, following Jcenter sunset

### ISSUE THREAD

**Issue by nwagu** [aminography/PrimeDatePicker#54]
For both primedatepicker and primecalendar libs

**Comment by Sabboo** [comment]
Any updates on this?

**Comment by rama-2402** [comment]
@aminography  Any updates on Migration from Jcenter?

**Comment by aminography** [comment]
Hey all, I'm on it. It will be available soon.

**Comment by abdulrahman-ahmad** [comment]
@aminography any updates or ETA of the  migration? 🙏

**Comment by aminography** [comment]
Hi all.
There was a problem with my domain that took a long time to solve. Fortunately, it is available now, so I've just published the library on MavenCentral.
Sorry for that!
BR.
