### ISSUE TITLE
disable future days

### ISSUE THREAD

**Issue by iceberg1369** [aminography/PrimeDatePicker#58]
Hello, 

list of disabled fays could be passed to calendar by disabledDaysList property. but is it possible to disable from specific day onward? eg from today to end

**Comment by iceberg1369** [comment]
for everyone else come across

`        var calendarType = CalendarType.PERSIAN

        val maxCalendar = CalendarFactory.newInstance(calendarType)

        val minCalendar = CalendarFactory.newInstance(calendarType)

        maxCalendar[Calendar.MONTH] += 0

        minCalendar[Calendar.MONTH] -= 5

        primeCalendarView?.maxDateCalendar = maxCalendar

        primeCalendarView?.minDateCalendar = minCalendar
`

**Comment by aminography** [comment]
Hi!
You did right. It’s just needed to set the `maxDateCalendar` for today.
BR.
