### ISSUE TITLE
select several days in one step

### ISSUE THREAD

**Issue by mohsenmdb** [aminography/PrimeDatePicker#7]
Hi, I want to select several days in one step, but you don't have this type in the [PickType](https://github.com/aminography/PrimeDatePicker/blob/master/library/src/main/java/com/aminography/primedatepicker/PickType.kt) class.
please implement this type in your project.

**Comment by aminography** [comment]
Hi; Ability to pick multiple days is provided using. Please upgrade the library version to [1.0.16](https://github.com/aminography/PrimeDatePicker#version-1016)

**Comment by mohsenmdb** [comment]
thank you, you are my hero

**Comment by mohsenmdb** [comment]
> Hi;
> Picking multiple days is now available. Please upgrade the library version to [1.0.16](https://github.com/aminography/PrimeDatePicker#version-1016)

thank you, you are my hero
