### ISSUE TITLE
Hijri calendar showing wrong Calendar dates

### ISSUE THREAD

**Issue by venkat-osv** [aminography/PrimeDatePicker#73]
1. Hijri Calendar showing wrong:

Ex: Civil Calendar date: 13 february 2023 Monday 
Hijri Calendar date is shwoing: 23 Rajab 1444 Monday.

but actual date in hijri calendar is 22 Rajab 1444 Monday.

**Comment by venkat-osv** [comment]
i have set dateAdjustingOffset = 0 then its wokring

**Comment by MahmoudLkashef** [comment]
you saved my day dude @venkat-osv
