### ISSUE TITLE
Change calendar type to the Jalali, Hijri and Gregorian

### ISSUE THREAD

**Issue by bkhezry** [aminography/PrimeDatePicker#9]
The standard name using for the calendars didn't correct.

**Comment by aminography** [comment]
These names are contractive and your suggested ones are preferential. So, it doesn't mean they are incorrect! You can read about `Persian Calendar` [here](https://en.wikipedia.org/wiki/Iranian_calendars) and [here](https://en.wikipedia.org/wiki/Gregorian_calendar) for `Civil`.
